# Generated by Django 2.2 on 2023-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_db_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_platform',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
