# Generated by Django 2.2 on 2023-05-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_href',
            name='url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
