# Generated by Django 2.2 on 2023-05-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20230510_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('monitor_time', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='db_href',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
